version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    command: "deno run --allow-net --allow-env src/index.ts"
    environment:
      - PORT=3000
    ports: 
      - 3000:3000
    volumes:
      - "./:/workspace"
    