version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=key.json
    ports: 
      - 80:3000
    volumes:
      - "./:/workspace"
    